stages:
  - build
  - test
  - docker
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:spring-latest

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build:
  stage: build
  image: maven:3-jdk-8-alpine
  script:
    - ./mvnw clean compile

test:
  stage: test
  image: maven:3-jdk-8-alpine
  script:
    - ./mvnw test

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  environment:
    name: production
  script:
    - kubectl config use-context your-k8s-context
    - kubectl apply -f deployment.yml
