stages:
  - build
  - test
  - docker
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:spring-latest

build:
  stage: build
  image: maven:3-jdk-8-alpine
  script:
    - chmod +x ./mvnw
    - ./mvnw clean compile

test:
  stage: test
  image: maven:3-jdk-8-alpine
  script:
    - chmod +x ./mvnw
    - ./mvnw test

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:19.03.12-dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  environment:
    name: production
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_FILE" > ~/.kube/config
    - kubectl apply -f deployment.yml
  script:
    - kubectl apply -f deployment.yml
